### ISSUE TITLE
I'm having issues with avatars that have layered clothing

### ISSUE THREAD

**Issue by vernilla** [Daw588/vanita#3]
Hi! Thrilled to find this extension!

I started saving my old avatars into it, but I'm having some trouble with ones that have layered clothing. I use BTRoblox's layer restriction removal flag, but not all the avatars affected make use of this, I don't think. I don't have enough avatars to test with or time to sit down and do it at the moment, unfortunately.

Still, any info you need...logs, console, outfit specifics, I'd be happy to provide!

Expected behavior: I click an avatar, the page reloads, I have the avatar equipped (rad).
Actual behavior: I click an avatar with no layers, it works as expected. I click an avatar with layers, nothing happens and the page stops reacting properly. I'm not sure when this happens, but at some point during me clicking and refreshing, the names of them sometimes change to TEMPORARY.

![image](https://github.com/Daw588/vanita/assets/75288193/f8701e1f-2643-4069-b6db-bd9b4d02a0ff)

The two seen here named TEMPORARY, as well as the 'beta sally' on the list are all layered, and all originally had names -- sally 2023 and baron 2023 are the renamed ones.

**Comment by Daw588** [comment]
Thank you for your report, I am aware of the issue, although I did not act on it, as I didn't know whether it was worth fixing given the low amount of users utilizing this extension, if any. I suspect the issue is related to the fact that I am presumably using an older version of the Roblox API, which does not support layered clothing. Since you rely on this feature, I will try to fix it as soon as I can, though it can take up to a month until I get started; it solely depends on whether I find some free time to work on this. Additionally, if you will be using the extension through the Chrome store, it may take a good while before it gets updated as the extension needs pass manual review process, just keep that in mind.

**Comment by vernilla** [comment]
Thank you!! I'm excited for it! I have some folks excited for it too now! I had no idea this extension existed but I'm def gonna be sharing it with folks <3

**Comment by Daw588** [comment]
I couldn't build the extension anymore, thus I decided to rewrite it from scratch, and I am confident that it will be significantly better. Here is a roadmap:
- [ ] Export and import support.
- [ ] Backup to cloud support (though I'm unsure how I'm going to go about it, might be its own update).
- [ ] Save extension outfit as Roblox outfit.
- [x] Layered clothing support.
- [x] Single click outfit change without the need of an empty Roblox outfit slot.

I will update you once I get these sorted out.

**Comment by vernilla** [comment]
Eee, I'm excited! Thank you for taking this on!!

**Comment by Daw588** [comment]
I'm almost done, though there is a bit of things that I need to polish out, before I can release it. I don't want to keep you in the dark, so here is some screenshots:
<details>
  <summary>Home</summary>
  <br />
  
![U6Bu9cY89m](https://github.com/Daw588/vanita/assets/44325281/429c9a66-3fed-4110-b2ba-634a3142cb85)
</details>
<details>
  <summary>Home (options expanded)</summary>
  <br />
  
![aIqWjDkagK](https://github.com/Daw588/vanita/assets/44325281/e4dc48ae-a143-4cb0-b27e-9d076a7bf5c7)
</details>
<details>
  <summary>Outfit Editor</summary>
  <br />
  
  ![eMQxXx6sRW](https://github.com/Daw588/vanita/assets/44325281/b1fb1e31-119e-4c84-bf88-64f2c92f1880)
</details>
<details>
  <summary>Outfit Editor (options expanded)</summary>
  <br />
  
  ![AJlQFYQsnI](https://github.com/Daw588/vanita/assets/44325281/a3bf9853-2629-408b-9d72-c214a8a4bfa9)
</details>

**Comment by vernilla** [comment]
Oh man, I didn't see this until now, I'm so sorry!! This looks awesome!

**Comment by Daw588** [comment]
It's fine. I was unable to work on this extension for a while now, might be able to finish it by this weekend, though no promises. I also wanted to see if there would be issues with thumbnails due to a concern that Roblox changed their system, which deletes thumbnails after certain amount of time (presumably 30 days), and I have confirmed it recently as some of my avatar thumbnails have gone missing, therefore expired, and are no longer accessible through the generated link. I will have to change the system a bit to save the thumbnail image data on local computer, along with the other metadata associated with saved avatars through this extension.

**Comment by Daw588** [comment]
Happy New Year everyone 🎆

I have good news to share. I stayed up the whole night to ensure that the update is complete on the first day of 2024. It is officially done as the update has been submitted for a review to Google Web Store. I know this update took a long time to be completed, but that's what it is when I have other responsibilities to fulfill. I will let you know when the review is complete, and hopefully it will pass so that there will be no further delays. Once you try it out, please let me know if the issue you originally mentioned has been resolved.

**Comment by Daw588** [comment]
Unfortunately when I was uploading the extension I removed a host permission, because I thought that "activeTab" permission would grant the host permission as stated per documentation but the wording is confusing. Today when I tried to use my extension to verify that it still works, it turned out to be broken because of this quick change. The version pending in review is broken, and sadly there is nothing I can do to cancel the review. I will have to wait few days up to weeks to have it pass review, and then upload the new version. This means that there will be a quite bit of delay, sorry 😞

**Comment by Daw588** [comment]
I have looked further into permissions, and it turns out that I don't need cookies permission nor host permission, which should significantly reduce review times. However, I already submitted 3.0.1 version, which requires host permission and it will take up to couple weeks before it may be approved. I never published extensions, before so I'm quite new to all of this. I will have to submit 3.0.2 version for a review once the 3.0.1 version is out of review process. I'm once again sorry for the delays 😞

**Comment by Daw588** [comment]
On my end the issue is resolved, and there doesn't seem to be any responses regarding this issue, so I will consider this as completed. If you encounter any issues, or would like to request a feature, or a change, feel free to open a new issue.
